# This is a generated file. Not intended for manual editing.
services:
  advcode2025_3:
    build:
      context: "C:\\Users\\ari\\RiderProjects\\AdvCode2025_3"
      dockerfile: "Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net10.0/AdvCode2025_3.dll"
    environment:
      DOTNET_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "advcode2025_3:dev"
    ports: []
    volumes:
    - "C:\\Users\\ari\\RiderProjects\\AdvCode2025_3:/app:rw"
    - "C:\\Users\\ari\\RiderProjects\\AdvCode2025_3:/src:rw"
    - "C:\\Users\\ari\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
